# Use an official OpenJDK runtime as a parent image
FROM adoptopenjdk:21-jre-hotspot

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY target/microservice3.jar /app

# Make port 8095 available to the world outside this container
EXPOSE 8095

# Define environment variable
ENV MICROSERVICE_NAME Microservice3

# Run jar file when the container launches
CMD ["java", "-jar", "microservice3.jar"]
