# Use an official OpenJDK runtime as a parent image
FROM adoptopenjdk:21-jre-hotspot

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY target/microservice2.jar /app

# Make port 8094 available to the world outside this container
EXPOSE 8094

# Define environment variable
ENV MICROSERVICE_NAME Microservice2

# Run jar file when the container launches
CMD ["java", "-jar", "microservice2.jar"]
